<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "package_b7_biesior_com"
 *
 * Auto generated by Extension Builder 2022-09-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Package for B7 DeadEnd instance',
    'description' => 'Package with templates an TS for B7 DeadEnd',
    'category' => 'templates',
    'author' => 'Marcus Biesioroff',
    'author_email' => 'biesior@gmail.com',
    'state' => 'stable',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
